### ISSUE TITLE
Draw the GPX track on the map

### ISSUE THREAD

**Issue by senarvi** [nemethviktor/GeoTagNinja#107]
When you open a GPX track in Lightroom, it shows the path that you have traveled on the map, in addition to the picture locations. This is in my opinion very useful.

![lightroom map module](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/594ae6fa-ea57-49f3-9f25-cd88253115a4)

GeoTag Ninja automatically tags the images with coordinates, when you open a track file, but doesn't show the track. Seeing the track on the map would be useful if you need to adjust the location of some pictures, because some GPS locations are inaccurate, the timestamps are inaccurate, or you haven't recorded the tracklog from the whole journey.

You can select multiple pictures and GeoTag Ninja will display all those pictures on the map. If you've taken pictures frequently, you can somehow see the path that you have travelled.

![geotag ninja map](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/050a4fac-7121-4b1c-acdd-e17112b589d2)

However, when you click one file to see the picture, the rest of the files will disappear from the map. Alternatively or additionally to showing the path I would suggest always showing all the files from the current directory on the map, but displaying the currently selected file with a different color. I think this would already make it a lot easier to place those files on the map that GeoTag Ninja didn't automatically place in the correct location.

Nevertheless, I'm really happy that we have an open source alternative to Lightroom and GeoSetter that already works really well!

**Comment by nemethviktor** [comment]
Hey, glad you're finding the app useful :)
Please refer to #104 as that's basically asking the same thing and I have a lengthy explanation on how to do (more or less) what you're after. Any more Qs shout ;)

**Comment by senarvi** [comment]
Indeed, that feature request is similar. I feel like it's not quite as helpful in the kind of workflow that I'm used to, though.

Maybe if you don't use a GPS tracker, connecting the markers with lines could be the best possible compromise. If the user loads a GPX file, I think it would be a lot more useful to see the track on the map. Looking at the Lightroom screenshot for example, connecting the picture locations by lines would look quite a bit different from the tracklog. I guess the more frequently you take pictures, the closer it will look like the tracklog.

![lightroom map module](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/4140eeb2-e2a8-4ec0-af27-2dd79a5575cc)

And perhaps the bigger issue is that only the selected pictures are shown on the map and not all the pictures from the directory. Lightroom keeps the loaded GPX tracklog on the map. When I click a marker on the map, I can see the picture. Or when I select a picture, the marker is highlighted on the map. The track stays on the map until I load a new one. So it's easy to finetune the picture locations along the track and place any files on the map that were not automatically tagged. In GeoTag Ninja, when I select a file from the directory list (in order to see the picture) the other files and the lines will disappear from the map.

Of course you have to prioritize things, so I can totally understand if this is unfeasible. Would be interesting to hear, though, if other users have similar issues, or maybe alternative workflows.

**Comment by nemethviktor** [comment]
Hi, 

I'm not against the idea but it needs refining. I've said this in the other ticket to the other user but I think most people use the software to tag and/or amend photos' geotags. What you're after is a different workflow and to some extent is a different logic. 

That said I've re-read your latest message a few times and I think I can do some of it in an iterative process and would likely involve a fair bit of ping-ponging between the two of us. [i don't mind that tbh :)]
 
So probably first step would be "put gpx tracks on the map" and then see how those go. However one thing is that I need to figure out how to do that. More to the point exiftool handles the GPX tagging but I am not quite sure it has the capability to just generally extract GPX coordinates w/o actually syncing them with a set of images so I'll likely have to use some different library for that.

**Comment by nemethviktor** [comment]
Btw, would you be okay to share the gpx track and the photos for dev purposes? I had been sent some in the past but I didn't keep them.

**Comment by senarvi** [comment]
At least, when it comes to tagging photos using a GPS track, the usability of Lightroom has been better than that of the other software that I've tried, so in my opinion that's a good reference of how it could work. It's always a good idea to implement things iteratively in as small pieces as possible, so let's start from putting the track on the map.

I didn't know that exiftool also does the GPX reading for you. I can also try to help if there's some task that could be done separately without understanding the existing code base, like parsing the GPX file. Otherwise you can probably do it faster yourself. I've never used C#.

Here's an example GPX file: [gpx-example.txt](https://github.com/user-attachments/files/16062420/gpx-example.txt)

It's a simple XML format, so it's probably not worth adding a new dependency for parsing it. However, exiftool seems to support other track file formats too. [This is how exiftool reads them.](https://github.com/exiftool/exiftool/blob/30e6ca0b462591262c6ac39f0261e6528262b142/lib/Image/ExifTool/Geotag.pm#L147) Unfortunately it's written in Perl. I don't know if people use other formats than GPX. For now we can decide to display the track only if it's in GPX format.

**Comment by senarvi** [comment]
[Here's an example how to read a GPX file in C#.](https://github.com/enricobenedos/GPXReaderLib/blob/master/GPXReaderLib/GpxReader.cs#L111) For plotting the path, we don't even need the elevation, so it's really simple.

**Comment by nemethviktor** [comment]
I'll prob need to use an external library. ET (exiftool) supports a variety of track file formats, not just GPX so it'd be useful if the plotter would generally follow suite. I think at least KML would be useful. I had a cursory look [here](https://www.nuget.org/packages?q=gpx&frameworks=netframework&includeComputedFrameworks=true&frameworkFilterMode=all&prerel=true&sortby=relevance) for relevant-looking packages  but want to ask in the [ET-forum first](https://exiftool.org/forum/index.php?topic=16184.0).

**Comment by nemethviktor** [comment]
Okay so I have a working preview of this (didn't upload it anywhere just yet) but I wanted to point out some things. 
For example in your file you supplied there are two distinct groups of coordinates. On the map this would manifest itself as:
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/74c6568b-4bae-4deb-8bb6-fb60c4bd9b8c)

.... and you'd need to zoom in to see the actual paths.
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/ce6d2e9c-bfa6-4afa-8683-926aa541e54c)
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/72aa7273-0a28-4d88-8b64-412cf7a23260)

This is because exiftool doesn't handle track segments. 
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/1cc974b9-e6f1-4d64-b157-978d60a83083)
(that's what basically comes out of ET)

**Comment by nemethviktor** [comment]
In the meanwhile, have a play w/ this https://drive.google.com/open?id=16laoPJcsJJz6mdkcjWvoQu6wWXiILbQy&usp=drive_fs version. There's now a checkbox at the bottom of the import-gpx Form to overlay the map path. Kinda experimental at this stage as you can guess + caveat the above post (re 2 paths.)

**Comment by senarvi** [comment]
Excellent! Yes, there are different track segments that correspond to different recordings.

I use this app for recording the GPS tracks: https://geotagphotos.net/
But it's probably the same thing with other tools: when you stop recording and later continue, you'll get different track segments.

Lightroom displays the different track segments disconnected. Actually, I would prefer it to work exactly as you described that it's working now. Sometimes I delete the gaps manually, because I'd prefer the tracks to be connected, by editing the XML file and removing every occurrence of
```xml
		</trkseg>
		<trkseg>
```

**Comment by nemethviktor** [comment]
I think we just cross-posted at the same time (so see above for my post)

The thing w/ grouping in ET is that "it's a feature not a bug". Because ET works on time-basis for it the fact that there are n (where n = 1+) tracks is entirely irrelevant, whereas Lightroom, as a software serves a different purpose.  That said, if it works for you, makes my life easier ;)
Try the link in my above post and see how it works for you.

**Comment by senarvi** [comment]
I installed the preview version. I import a GPX track, checking "Overlay Track file onto Map". For some reason I still don't see the track. It correctly geotags the images, but doesn't show the track. Just let me know how I can help with debugging this.

**Comment by nemethviktor** [comment]
If you don't mind sending (you can put on Google drive) your gpx file and
at least 1-2 photos that'd help ;)
This message has been brought to you by my Honor Magic5 Pro and myself. Any
typos blame the phone.

**Comment by senarvi** [comment]
Here's a Google Drive folder: https://drive.google.com/drive/folders/1guQmVZ3PcAyI7ezGp-JAXqJValDZW2Ml?usp=sharing

And screenshots of what I did, just in case I missed something:

1) Select the files in the folder.

![Screenshot 2024-07-05 162713](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/7c620207-71c1-440b-945c-a32db19e1c74)

2) Go to the import dialog. Open the track file, set the time zone offset to +1h, and chek "Overlay Track file on the map".

![Screenshot 2024-07-05 162758](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/da7a5faa-e570-4e67-afad-0d785ab3bccd)

3) Nothing appears on the map. I select the image files again. Now I can see the image files on the map, but no track.

![Screenshot 2024-07-05 162857](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/97b5ca6d-dcfa-46a7-a0be-bdbaa1123fdf)

**Comment by nemethviktor** [comment]
Works for me :)

![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/89b07f38-0359-4d0e-9eca-9055a53f54cf)

What's your Windows culture setting? (ie en-us, en-gb, en-fi...?)

![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/840a604c-6a3b-41e9-b35a-4df5a674a1bc)

(for me)

**Comment by nemethviktor** [comment]
Found the issue. The usual (i forgot to use culture independent parse.)
Funny you're the 3rd or 4th Finnish user that's active w/ requests so I actually have set up a Finnish virtual computer for easier testing. (why is the app so popular there? :))

Can you check the previous link please again. (you'll prob need to actively uninstall the app, don't worry, your settings are kept, because the build-date is the same as earlier today so Windows Installer will think it's identical in all aspects)

**Comment by pbranly** [comment]
Hi
I will use the beta for this now fantastic feature . Will it support json files from google ?
Phil

**Comment by nemethviktor** [comment]
Hi Phil, 

Nice to see you :) - I think so. It used Exiftool's built-in capability so if ET supports it then so does this.

**Comment by pbranly** [comment]
Ok fine
I Will test it tomorrow and report back to you 
I still use you software as this is the only one that supports easily json files. 
Even if those google json files give sometimes obscur results !
I tried to ask geosetter déveloper to add it in its beta version but there is no way to contact him
Good job! 
Phil

**Comment by pbranly** [comment]
Hi
It works with json files as well
Nevertheless, would it be possible to restrict the trace toi the selected photos ?
As you can see on the screen shot, I have all the traces for 2 years of google traces while I am working on photos during a few days in eastern part of France/ Belgium
Thanks
Phil
![2024-07-06_08-23](https://github.com/nemethviktor/GeoTagNinja/assets/22018509/29c319b9-8fae-4669-b2aa-0878f653c2f4)

**Comment by nemethviktor** [comment]
hi Phil, 

not really, if you think about it it doesn't make logical sense. the json file you have doesn't directly relate to photos and has a lot more timestamps than your files do as it's a path (ie a set of positions at various times) and so there's limited way to link up one bit of information with the other. 
i was saying above that i can include an option to visually represent groups of tracks on the map but that'd be based on deviation in the time-gaps from average rather than real trackpoint splits because exiftool doesn't know/care about those. 
the least comfortable but prob most useful option would be to manually split the json file you have into batches.

**Comment by senarvi** [comment]
Yes, outstanding! I didn't expect to have this feature working within a week! I can finally stop dreaming of getting the Map module working in the last non-subscription version of Lightroom. And shout out to the Finnish early adopters!

I'm curious, why the regional settings constantly give you headache? Is it because they affect the ET output that your parsing? In UNIX I would set the locale using environment variables to C before executing the child process. I wonder if you could do something similar.

In my opinion, the track should not be restricted to the *selected* photos - that would mean that when I select one photo, I don't see the track anymore - but it would be worth considering what photo selection should do. However, here are some other ideas that could solve @pbranly 's problem:

- You can manually edit the JSON file, deleting everything before/after certain date.
- The track import dialog could have start date and end date - only keep the track between these dates. Or something like the "crop" feature in Strava.
- Restrict the track between the first and last day of all the files in the directory.

We already talked about this, but just to reiterate, my main concern is that when I adjust the position of a photo, I'd like to see a preview of the photo. In Lightroom there are two ways to do this:

1. Select a photo from the list - Lightroom will highlight the photo on the map, so that I know which photo it is.
2. Select a marker on the map - Lightroom will show a preview of the photo.

All photo markers are shown on the map, regardless of which photo I select, but with a different color.

In GeoTag Ninja, when I select a marker on the map, it will show the coordinates. If it would also show the preview, that would be perfect.

I can see the preview if I select a photo from the directory list, but then all the other photos disappear from the map and the map view is reset back to showing the entire track. I'll illustrate this with a couple of screenshots.

I have selected all the photos and zoomed in to the area of the map where I'm working:
![All photos selected](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/65c983e0-1b16-454e-a3db-2174d30da5bc)

I select one photo from the list to see the preview. The other photos disappear from the map, and the map view is reset:
![One photo selected](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/69e09b57-3c8a-4fb8-a9c1-044898f375a5)

Anyway, that's just something I found inconvenient. Great progress with the software!

**Comment by nemethviktor** [comment]
Hi, 

Glad it worked.  :)
In no particular order:
- C# has some built-in assumptions about how a number should look like so it's not ET that's giving me grief but parsing any string value into numbers. I.e. in some regions of the world "one and half" is `1.5` but elsewhere it's `1,5`. Conversely `1.500` is still one and half someplace but `1,500` is one and half thousand elsewhere. So C# has to be instructed to attempt to discern the numbers based on 'local' logic of sorts and I have a tendency to forget about it because on `en-GB` culture (the one I use), "it just works". And then I occasionally forget to fire up whichever VM that has different language settings and thus not test.
- The track time crop is actually not a bad idea, I'll have a think about it.
- Specifically re: showing photos on the map: I know we're both kinda repeating ourselves but the problem is that if someone has a literal hundred of photos tagged w/ the same coordinates (e.g. my super old photo scans from wherever I grew up are all just tagged w/ that location) then showing them on the map would become crazy. Conversely clicking on a marker might select a lot of pictures. Also note that image selection drives marker display so I don't really want to create a recursion.
- Adding a different colour marker for non-selected items could be done but only as an option. Also note that it'd then zoom out to your full folder's coordinate list each time because the bounding box always zooms to the max coverage (like when you select a dozen photos now.)

**Comment by senarvi** [comment]
Thanks, I can now understand the locale issue.

I would imagine that if you have multiple photos that are tagged with the same coordinates, then you get multiple markers on top of each other. When you click on the marker "stack", it would select the topmost (which could be any of the photos). This is not possible?

Re: Image selection drives marker display. I guess there wouldn't be a recursion issue, but this would be unintuitive: user clicks a marker -> the image is selected -> all other markers are hidden.

I'm throwing in a few alternative ideas:

- When the user clicks a marker, the file name is displayed along with the location. Then the user can click the file in the directory list to see the preview.
- When the user clicks a marker, a preview of the file contents is display in a box. Below is an illustration.

![mockup](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/08bb9c53-c17c-4892-ae1d-5561e8b37281)

If we would display all markers, but the non-selected ones with a different color (let's say, gray), then every time I select an image, it would zoom out to the bounding box of all markers? That would indeed be very annoying. Is it possible to add a check that if the selected image is within the current map area, it won't zoom out?

**Comment by nemethviktor** [comment]
There's an "event", `selectedItemChange` (might have a somewhat different name, not looking at the code now) - that drives what gets sent to the map. Basically there's a html file somewhere in the Resources folder and there's some javascript magic taking place each time the user clicks an item (or a number of items) on the main listView (grid). So if we introduced a method where the clicking-on-the-marker does anything to the selection on the listView that would trigger said event and create a recursion. 
- So stuff like "show file name(s)" is doable, although I think it'd be something like `d:\temp\myfile.jpg [and 200 others]` in certain cases, rather than actually listing a shedload of paths.
- The preview I think is doable although it'd work only on one image (ie if you have 200 w/ the same marker, I think it'd just be ignored altogether.
- There's no way to read what's on the map - in particular wrt coordinates. When the map is drawn `leaflet` (the map overlay provider) gets sent a set of coordinates. If you're more into APIs then it's like a PUT. But there's no GET function, so if you scroll anywhere or do anything on the map (zoom etc) I can't check you've done anything. The only reason why I can check that you may have clicked on a marker is because that's a somewhat different logic.

**Comment by nemethviktor** [comment]
Okay, so same link as above (sorry...) some new changes for anyone to play with...
- added a checkbox to only include those track elements that overlap with the selected photos' min-max dates (_dates_, ie _time_ is ignored)
- wrt the above ET _always_ reads UTC time from track data so i tried to accommodate for the TZ changes triggered by the user, the little testing I have done showed this works (i did test on the Finnish VM this time...) but please play around with it.
- the frmImportGPX (aka the import Form) is now scrollable. you might not see the OK button right out but it's still there, just scroll down. the Form was getting a bit long and I'm too lazy to reorganise everything onto separate tabs.

Me off to 💤 .

**Comment by pbranly** [comment]
Hi Victor
Fantastic for me
Thanks
Phil

**Comment by senarvi** [comment]
> There's an "event", `selectedItemChange` (might have a somewhat different name, not looking at the code now) - that drives what gets sent to the map. Basically there's a html file somewhere in the Resources folder and there's some javascript magic taking place each time the user clicks an item (or a number of items) on the main listView (grid). So if we introduced a method where the clicking-on-the-marker does anything to the selection on the listView that would trigger said event and create a recursion.
> 
> * So stuff like "show file name(s)" is doable, although I think it'd be something like `d:\temp\myfile.jpg [and 200 others]` in certain cases, rather than actually listing a shedload of paths.
> * The preview I think is doable although it'd work only on one image (ie if you have 200 w/ the same marker, I think it'd just be ignored altogether.
> * There's no way to read what's on the map - in particular wrt coordinates. When the map is drawn `leaflet` (the map overlay provider) gets sent a set of coordinates. If you're more into APIs then it's like a PUT. But there's no GET function, so if you scroll anywhere or do anything on the map (zoom etc) I can't check you've done anything. The only reason why I can check that you may have clicked on a marker is because that's a somewhat different logic.

Thanks. I can now somehow understand the problem.

I didn't realize it earlier, that this is also different from Lightroom:

- Lightroom displays one marker per image. There can be multiple markers in the exact same spot. If you move a single marker, another marker that was below it is revealed.
- GeoTag Ninja displays one marker that represents all the images that are in the same spot. If you move a single marker, all the images will be moved. If you want to move a single image, you have to select it from the file list.

For me it would be most intuitive to (A) display one marker per image and display a preview box when the user clicks a marker.

The next best option in my opinion would be (B) to display a preview of one image (any image) from the stack. There could be also this kind of stacking symbol to indicate that there are multiple images:
![preview of stacked images](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/b9c2dd9f-8f97-48c9-a7a2-adb6046f0b0c)

Option B works for me as well, because I rarely have multiple images with exactly the same coordinates. The downside is that if you do have multiple images with the same coordinates, you can only separate them by selecting one of them from the file list. And when you select an item from the file list, the rest of the images will disappear from the map.

I was trying to install Visual Studio to be able to build the software and understand its logic better, but didn't manage to do that yet.

**Comment by nemethviktor** [comment]
Hi, 

I'm not saying this isn't doable but some of it is beyond my understanding of javascript (though I figure GPT can always help) and some of it isn't practical at this point. In fact the whole preview thing might be a hard-start. I'll be a bit more detailed as you said you're likely to look into the code. 
Here's what happens currently when the user loads a folder and interacts with an image. (i can't seem to format advanced bulletpoints here so it'll be a bit random)

1 Folder entry
- assuming the user is in normal mode (not "track-the-path-mode") they enter a folder, GTN parses the tags of every file in the folder
- alternatively if the user is in track-parse mode then the track-file gets read and the coordinate-pairs get assigned into a list (technically a dictionary for reasons that aren't relevant here.) and then the interaction w/ `leaflet` (see below) gets fired up
- note that previews are not generated at this point. see below

2 image interaction:
- as mentioned in an earlier comment we use `leaflet`. it's a javascript extension to handle map related stuff. there's a `map.html` in the Resources folder and that has a hard-coded reference to `{ HTMLAddMarker }` (inc the curly brackets). if you're planning on diving deeper into the code you'll find the exact same string in `internal void Request_Map_NavigateGo()` of `frmMainApp``, part of that is to convert the values of the selected images to javascript and then it gets sent to the html file and the whole thing is rendered on the fly:

![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/070edd7f-f0f3-4591-a441-fddb660a30d6)

now a `marker` as per documentation -> https://leafletjs.com/reference.html#marker has `lat`, `lng` and a bunch of other things that aren't being used at the moment. I hazard that as per https://leafletjs.com/reference.html#icon the image could somehow be coerced to show (admittedly though https://leafletjs.com/examples/custom-icons/ makes it more unlikely to do what we are after here.). but...
- the list of markers in our code is actually a set `internal static HashSet<(string strLat, string strLng)> HsMapMarkers` so it doesn't take duplicates. this is on purpose and while it can be changed to a list if other users do have 1000 images w/ the same location tagged then we'd be adding 1000 markers each time the user does a 'select all'. That needs rendering and is slow. 
- there's no option (ref marker options/properties above link) to add any sort of a tag to the marker. so basically the reason why it does work okay that the user clicks on a marker and GTN reads the `lat` and `lng` strings is because those are valid properties of a marker but there isn't anything other here (relevant that is) to pull back info like filename (as in "instruct the code to move one file's coordinates but not the others" or some such)

3 previews:
-  the reason for previews not being created right until the user clicks on an image is that 1) each preview takes a portion of a second to make (so doing a "generate all previews on a big f...ing folder upon entry" is a bad idea) and 2) espc with some of the larger RAW files it takes longer and is heavy on the CPU. Windows (more precisely .net framework 4.8 [which is from the Windows 7 era, so think of this is a "Windows 7-era software" wrt to capabilities]) does not support more modern images natively so for most RAW files ET (exiftool) has to be called to generate the preview. 
- preview generation is explicitly only allowed for 1 image at the time (even if you do a select-all the bottom left image pane will show one only because the code just takes the first of your selected items and makes the preview for that)
- now that i think of it even displaying previews are problematic. the `icon` thing isn't likely to do what we are after and actually the preview files don't exist half of the time [e.g. jpg previews _are_ supported by Windows so they are read in as an ephemeral image without being written to the disk but RAW images do get converted to a JPG file that does have to sit on the disk].
- so wrt your request, if you have multiple selection, _all_ the previews would all need to be generated first (takes time) _then_ the map would need to update (so that i can point to preview images to be loaded as a source for the icon [but still no _tag_])

4 regenerating the html file: 
- the html file is actually regenerated each time the user clicks a different image because usually users click one image at a time and the marker needs to be updated. 
- if we change this to allow for active and inactive files (actually as per documentation link above there is no property for individual markers to be different from the rest, although this is where `icon` could be used as intended by the leaflet-developer) then the html file needs to be regenerated with a lot of content each time the user does something.

sidenote:
in the map.html we currently have 
```
map.on('click', function onMapClick(e) {
            //marker
            //    .setLatLng(e.latlng);

            popup
                .setLatLng(e.latlng)
                .setContent(e.latlng.toString())
                .openOn(map);

            window.chrome.webview.postMessage({ "lat": e.latlng.lat, "lng": e.latlng.lng, "isDragged": false });

        });

```
note though that the `click` function is an `onMapClick` event, not an `onMarkerClick` event, ie it's just coincidence that there happens to be a marker on the map at that coordinate-pair. clicking on the marker itself isn't discernible from the rest of the map so expanding a popup _and knowing_ it's a marker click is either not possible or i don't know how (that said i'm not good at JS at all)

... so if we can somehow amend the popup to do more advanced stuff that can be experimented with but with all the above in mind i'm not convinced it's viable so the likely option will be the original idea of `d:\temp\myimage.jpg [and 200 others]` I'm afraid unless someone can come up with a complex javascript hack.

**Comment by senarvi** [comment]
Got it. So it's not as simple as one would think. Thanks for the detailed explanation. I hope that I'll have some time to look at the code once my holiday starts. I'm not very hopeful that I can come up with something clever, but I'm definitely interested to at least understand how it works, since this tool is really valuable for me.

**Comment by nemethviktor** [comment]
Sure thing. I'll close the ticket for now, if you find some ways to make the markers better, shout :)
