### ISSUE TITLE
Auto Updater incorrectly claims that there's an update available

### ISSUE THREAD

**Issue by ForgeSource** [nemethviktor/GeoTagNinja#110]
**Describe the bug**
Started GTN today. Got pop-up message that a new version (8890) was available. Agreed to update, but update failed, and I cannot see 8890 on here.

**To Reproduce**
Start GTN. Agree to update when offered.
(Unable to reproduce, as restarting GTN - multiple times - does not offer to update)

**Expected behaviour**
8897 Release Notes say: _"Added an auto-updater. It's a bit tricky to test but I think it works. Report bugs pls."_

**Screenshots**
Only happened once, and unfortunately I did not take a screen shot, nor take a note of the failure message.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Language/Culture en-GB
 - Full Path of Picture: N/A

**Additional context**
Only happened once, but 8897 release notes request that any updater bugs be reported.

**Comment by nemethviktor** [comment]
Hmm thanks. I'll have real difficulties testing that out because the build number changes each time I rebuild. But in fact there hasn't been a release since 8897 so unsure why it's doing that. I'll try to debug nonetheless.

**Comment by nemethviktor** [comment]
Ok so the issue is that the build number is supposed to be a count of days past 1/1/2000 and that works but the API call I made is looking at the publish-date. So what happens in this case is that the software build date and the upload-date aren't the same and that's causing confusion. I know why I wrote the code like so but I'll change it around.
