### ISSUE TITLE
geotag ninja should use gps files for geotagging photos

### ISSUE THREAD

**Issue by pbranly** [nemethviktor/GeoTagNinja#13]
As in the geosetter program, it should be possible to geotag batch of photos from existing gps files with options as in the geosetter program

for future !
Phil

**Comment by nemethviktor** [comment]
Can you provide an example GPS file please. Preferably a "real" one. I can then ponder on how to add that in.

**Comment by pbranly** [comment]
could you provide me mean to mail in private mode ?
I dont wish too much to share my positions !
phil

**Comment by nemethviktor** [comment]
Either can you pls send an email to _nemethv_ on gmail or if you prefer you can upload the file any place, you can change the numbers etc but I need the format/structure of the file to be real. I don't mind if all the coordinates are [51°28′40″N 0°00′05″W](https://geohack.toolforge.org/geohack.php?pagename=Royal_Observatory,_Greenwich&params=51.4778_N_0.0014_W_) but keep to the original format please.
Alternatively again I'm assuming the file is of something of an established standard so if you point me in the right direction to that standard I can work from there.

**Comment by pbranly** [comment]
I just sent a private mail with files and general description of my procedures
Phil

**Comment by pbranly** [comment]
for information 2 screen copies 
first one is made from positions from pixtrack
second one from positions from json files from google
As you can see there are differences but this could be acceptable when you take a lot of photos in vacations and you dont remember where !
![2022-10-16_18-28](https://user-images.githubusercontent.com/22018509/197546900-78a70718-bceb-4bdc-818d-9a9ac350b274.png)
![2022-10-16_18-30](https://user-images.githubusercontent.com/22018509/197546912-89535909-8d19-4564-bb17-e9ae33ad2737.png)

**Comment by nemethviktor** [comment]
Received, thank you -- I'll have a look at this a bit later. I'll first do the "external path for exiftool" 

Actually a few questions. Admittedly I've never used this particular functionality in geosetter so a little unsure about the requirement. 
- You'd like to parse the gpx/json files and put the coordinates onto the map like in the screenshot, right?
- After that happens, what would be the next step? (just use the marker as a basis point for tagging?)

At the moment I'm not sure how to put multiple objects onto the map so I think this might be a longer term thing. It (the map and the markers) is a Javascript thing that I haven't really dug into yet.

**Comment by nemethviktor** [comment]
I'll see what I can do about it - as a first step the next release will finally work with multi-select on the map. That lack of feature has been bugging me ever since the first release.
![image](https://user-images.githubusercontent.com/58767235/197881082-58d3a06b-f126-47e7-9814-623d3012100d.png)

**Comment by pbranly** [comment]
Fantastic !
I will be happy to help you for any test
Nikon D5 …. Fine … I just have the D750 ! But I find it heavy. That is the reason I use more and more the Sony RX10 especially compared with d750 + 150-600 mm ……

**Comment by nemethviktor** [comment]
Same link as in the "French thread" but just putting here for logging purposes.  -> https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=sharing 
If you feel like playing around with multi-select. Doesn't yet have the tag-import thing but just more or less the version from which the screenshot is.
Also changed a bit of logic so that it doesn't check each time for new version but just once a week. (kinda relating back to #11 )

**Comment by pbranly** [comment]
same as for the language: no map any more

**Comment by pbranly** [comment]
![2022-10-26_15-48](https://user-images.githubusercontent.com/22018509/198043727-3d22c2eb-d9f2-4572-9d03-18e73237296a.png)

**Comment by nemethviktor** [comment]
![image](https://user-images.githubusercontent.com/58767235/198059592-e6edd00d-6076-4122-a997-bf34a177190a.png)

Try again please, same link as above. (tested this one on Hungarian, which I think is that same culture-setting as French so should be ok now).

**Comment by nemethviktor** [comment]
I'll have to have a proper look at what Geosetter was/is doing :)

Re languages: yeah, HUN isn't quite the same family as FRE but from a coding perspective is the bloody numbers that cause a headache. E.g. in English a decimal is a dot whereas in others (like FRE/HUN) it's a comma. Same annoyance w the thousand separators (for UK that's nothing/comma but I think for a bunch of countries it's space) 
So like the number between one and two for me is 1.5 whereas for you it's 1,5 --> most systems expect to work with the English rules (the map API certainly does) the problem was in this particular case that Windows just takes the numbers according to the local "culture setting". So for you it wasn't working because the coordinate 51.1234 was firing off as 51,1234 to the map and it didn't know what to do with it and I forgot to account for it in the first attempt.

**Comment by pbranly** [comment]
Babel Tower issue !
Congratulations 
It will be a very good tool 
Phil

**Comment by pbranly** [comment]
I think that the advantage of geosetter is to give a MMI to the basic command line for exiftool.exe

**Comment by pbranly** [comment]
Hi,

    So the idea is that it pulls the GPS info from the GPX/JSON files based on time-stamp and just assigns the position of the "nearest timestamp" to any selected photo?

>>>>>>>>>> yes this is the philosophy

    For the GPX files the "source of truth" isn't the file name-date (e.g. 2022-10-14_15-53-42.gpx) but in each of the files the closest <time>2022-10-14T15:53:43+02:00</time> to the picture-taken-TS? [timestamp] (and take <trkpt lat="xx" lon="xx">)
    For JSONs it's the "simplifiedRawPath": { "points": [{ "latE7": xx, "lngE7": xx, "timestamp": "2022-10-01T08:26:12.704Z"}] (and just take the two E7 values...)

>>>>>>>>>> In both solution, I sincerely dont know as this is really shared by exiftool program. 
for the json solution, here is the discussion link with Phil, when he developped the version that supports such file.

https://exiftool.org/forum/index.php?topic=13671.msg74019#msg74019

nevertheless, I think that the minimum command line to tag photos with at least gpx and json file is:

exiftool -geotag positions/*.* "-geotime<${DateTimeOriginal}+02:00" . -api GeoMaxIntSecs=1200 photos/*

I just verified that this line works with either GPX or JSON file (so the "positions/*.* "" part of the command as I copy my positions files in /positions)
DateTimeOriginal is also necessary (needs some tweaking between file coming from GPX and file in UTC coming from google
and GeoMaxIntSecs is the precision needed between 2 photos (with my GPX file coming from my iphone, I can have very short value but from the JSON one, I have to increase otherwise, exiftool does not find many photos

I think that first step would be to have those 2 last parameters only in your MMI and a routine that should launch this command. 
+ for sure all the stuffs about directories ...... !

for information, this commands generates new photos with positions written in the photo and keep the existing ones with a additional _original suffix to the extension name

What do you think ?
I my English clear enough ?
Phil

**Comment by nemethviktor** [comment]
Thanks for the updated -- I'll have a proper look next week.

**Comment by nemethviktor** [comment]
Just a follow up, Phil has provided a logic that could work -> https://exiftool.org/forum/index.php?topic=13671.msg74019#msg74019 
I'll look at it next week.

**Comment by pbranly** [comment]
Fantastic what a team !

**Comment by nemethviktor** [comment]
Ok can you pls have a look at - https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link
Do back up your files on this occasion as it's very experimental.

**Comment by pbranly** [comment]
hi
I made very quick tests and hope I will make more this afternoon and to morrow
great job !
Phil
![2022-11-05_08-42](https://user-images.githubusercontent.com/22018509/200114427-4d4927bb-085f-48b3-a74c-fb2061cf5f47.png)
![2022-11-05_08-41](https://user-images.githubusercontent.com/22018509/200114431-fd2b5b98-5763-4cee-975d-70aa5face81b.png)
![2022-11-05_08-38](https://user-images.githubusercontent.com/22018509/200114433-96f6ddef-da3d-4f2d-940c-1dce2e02ce3a.png)
![2022-11-05_08-37](https://user-images.githubusercontent.com/22018509/200114435-e1f1cd41-07a4-45ca-9604-20d8e367c07c.png)
![2022-11-05_08-34](https://user-images.githubusercontent.com/22018509/200114438-5bd08d42-9590-4b39-9025-1c39445c8df4.png)
![2022-11-05_08-32](https://user-images.githubusercontent.com/22018509/200114440-2e91f02d-5cb6-4d4e-879f-8f68a36d4ccd.png)
![2022-11-05_08-31](https://user-images.githubusercontent.com/22018509/200114442-1453e46d-d243-4356-9723-0904d65ae4ce.png)
![2022-11-05_08-30](https://user-images.githubusercontent.com/22018509/200114443-e536fbe8-3dce-4e17-a283-4a00411ab3df.png)

**Comment by nemethviktor** [comment]
Hi again,

ok so quickly 
- French translations that aren't from you are google translated. (feel free to suggest better/shorter ones)
- "replace originals" -- that's just to use backups or not. basically if it's off then no backup file is created when saving.
- "why keep xmp" -> turn off sidecar creation in the settings you asked
- "no value" -- can you be specific as to what precise settings you used for the import? like what xmp file, what dropdown values, what timezone etc. i can't quite debug without them -- also when the lat/long is updated after import that wipes the city/state/etc settings for the file. that's on purpose, just "get from web". 
- "no processing message". i think that's on purpose because "-geotag" works differently in exiftool than the rest but i'll think about how to bring it back in. might or might not be possible
- "no possibility to see positions on the map" -- i don't understand that. it's a Save File? question. if you mean that city/state etc are missing then "get all from web" first. alternatively i can auto-trigger that (see above at "no value")
- "should be on map" - again please provide precise details of various combinations used. otherwise i can't debug


I'll be off for most of the weekend but will be back on Monday :)

**Comment by nemethviktor** [comment]
Kind of a +1 and a bit of explanation on why some of your data might not show. The TLDR is that you need to adjust the timezone and DST. So in your case, if your pics were taken in Rome and the photos are TZd as they are then you prob need to set the TZ to Rome and then turn on DST. [Paris will also do but prob turn on DST because you took them while DST was on]
Here's a rundown of how this whole process runs, things it can do and things it cannot do.

1. user selects a file/folder that has gpx/json/whatnot files
2. user sets the rest of the settings and presses OK
3. exiftool parses the track files and tries to marry them up with image files. 
4. the actual _write_ process doesn't happen, instead a dummy file gets created somewhere that the user doesn't see. this file is specific to the image file. 
5. GTN parses the dummy file and queues up things to write
6. user chooses to write and completes the process

A few "problems" here:

1. the process (from the perspective of image files) only works on whole folders - while it's not impossible to queue up a bunch of commands for individual image files, there is no benefit to it 
2. there is no way to parse the track files and export them without marrying them up with image files. exiftool  (ET) doesn't have that capability and i won't code it because it's a major pain in the backside because ET can only deal with a(n admittedly wide) range of track types, so there is no point in me re-inventing the wheel here. even so, a track file could contain 100s if not 1000s of coordinates and if we were to query each of those for a TZ setting via an API then we'd get banned from the API for overusage. an outcome of this is that there is no way to pre-pull coordinates, then automatically figure what time zone they are and apply them separately. this is why the user needs to pre-set that in the dropdown.

**Comment by nemethviktor** [comment]
+2 edit/amend:
I'll adjust the auto-pull from web after a coordinate change to happen so user won't need to do it.

**Comment by pbranly** [comment]
For the settings menu French is OK but I am afraid it does not reflect a good understanding.
Sometimes, it is better to imagine what it should be in English first
- Ajouter/écraser xmp dans le fichier: add/overwrite xmp in the file ? Which file ? Overwrite which xmp ? 
Is it the setting to choose either add positions in the existing photo file or create an additional xmp along the photo file ?

- Ajouter/remplacer sidecar XMP: i am afraid that I don’t understand Sidecar and what it is used to. What is the benefit for a basic photographier who does not anything about informatic ?

-  Remplacer le fichier d’origine: replace original file ? Which file ? What’s the relationship with first setting ?


Sorry for noob ( or look like noob !) questions but I prefer clarification before giving new translations 
Phil

**Comment by nemethviktor** [comment]
re: Settings, xmp/sidecar files, overwrites:
If you'd like to see the English you can set the language to English. The actual functionality logic is copied from GeoSetter (GS) but I'll try to explain. 
- What sidecars do: I _think_ it's part of the Adobe workflow. RAW files when edited in ACR (Adobe Camera Raw) get created an extra XMP file in addition to modifying the image itself.. Also exifTool itself has settings whether to read or ignore and whether to prioritise high or low sidecar files, built-in xmp tags and built-in exif tags. GTN handles these as part of the code. I don't _know_ why the sidecars came to exist (there are some wiki articles [here](https://en.wikipedia.org/wiki/Sidecar_file) and [here](https://en.wikipedia.org/wiki/Extensible_Metadata_Platform) but they are limited use), but it's "normal". GS had this option where most RAW files and some TIFF based files would default to creating/editing sidecar files. If you look in GS that's by default disabled for JPG based stuff so I copied the logic here (also in ACR JPG files don't get created sidecars unless the user explicitly asks). Not sure this answers your Q but hopefully useful.
- "add/overwrite xmp" -> that's the sidecar xmp outlined above.
- "replace original file" -> the image file (jpg, cr2, nef, arw...). If you _don't_ replace it then the process will create a backup of the original. Again this is inherited behaviour from ex-GS logic, it does the same.

**Comment by pbranly** [comment]
if i well understand, whatever the correct words are, if I want to save the positions inside the picture file and create a save of the original, I need to have such settings:
"add/overwrite xmp in file" : activated
"add/rewrite xmp sidecard" : deactivated
"overwrite original file": deactivated

but the result of the process is that I have for each photo the original with positions inside, a XMP file (no need in that case)  and no backup 
this means that second and last option do not work

I tried also to have no change in the picture file and have a sidecard xmp so options :desactivated, activated, deactivated but after validation of such settings, when I verify the settings, the first one is always activated so it does not work as "add/overwrite xmp in file" : deactivated as it is not kept in consideration 


and here are the screen copy of my configuration inside geosetter with texts in english
![2022-11-05_17-53](https://user-images.githubusercontent.com/22018509/200132017-ca2d82ce-ae91-42d7-bfcf-030786422f77.png)
![2022-11-05_17-55](https://user-images.githubusercontent.com/22018509/200132018-eba5ed18-d476-4283-98b3-44ff72d3af63.png)

Phil

**Comment by nemethviktor** [comment]
Hi Phil, 
Thanks for those I'll have a look next week. The various settings (the three in Settings that don't work now) had worked at the time of the initial release but I haven't tested them since. It's possible I've modified something over the course of the past some months that broke it.

As for the two other things you've flagged:
- It's _probably_ possible to add in the Max Time Diff setting. It requires poking the exiftool API, which I haven't done but I'm guessing it's possible.  See below nonetheless.
- The interpolation I'm not sure about. See below from exiftool documentation:
<html>
<body>


GeoMaxIntSecs | Maximum interpolation time in seconds for geotagging. Geotagging is treated as an extrapolation if the Geotime value lies between two fixes in the same track which are separated by a number of seconds greater than this. Otherwise, the coordinates are calculated as a linear interpolation between the nearest fixes on either side of the Geotime value. Set to 0 to disable interpolation and use the coordinates of the nearest fix instead (provided it is within GeoMaxExtSecs, otherwise geotagging fails). | A floating point number | 1800
-- | -- | -- | --
GeoMaxExtSecs | Maximum extrapolation time in seconds for geotagging. Geotagging fails if the Geotime value lies outside a GPS track by a number of seconds greater than this. Otherwise, the coordinates of the nearest fix are taken. | A floating point number | 1800


</body>
</html>

My understanding (but I may be incorrect) that the two things you're asking are defined based on the two settings above but they both default to 1800s . So I'm not entirely sure if adding in the settings will change much.

**Comment by nemethviktor** [comment]
Okay, same link as above [here](https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link).
Changes:
- I've had a 2nd look at the problematic settings re xmp files, overwrites and whatnots. I've tested it with an ARW file and it works now. If it still doesn't work for you, shout, but do ensure you have your setting per extension (so if you set it for ARQ but not ARW then it won't work for ARW)
- I've added in the extrapolation/interpolation options. There is no setting in exifTool doc like "don't use future TSs" [ts = timestamp] so there is no such option here.

**Comment by pbranly** [comment]
Hi  this is fantastic.
I just made 5 mn tests this morning 
when trying to untick the overwrite original file (so without the -original backup) there is a message for each photo
when it is ticked its works

I will make additional tests to day and next days
Phil

![2022-11-07_08-20](https://user-images.githubusercontent.com/22018509/200251054-df009167-b7f2-42ac-9f67-770336359ff3.png)
![2022-11-07_08-26](https://user-images.githubusercontent.com/22018509/200251057-52935d69-c0bd-4bd2-90af-dbafa788f8bf.png)

**Comment by nemethviktor** [comment]
That shouldn't be related to the backup or overwrite. Unauthorized just means that your geonames username/password combination is not valid (or some such, albeit very likely as it's just a reply from the API, which is entirely independent from the app)

**Comment by pbranly** [comment]
Surprising because when it is ticked I can choose either having sidecars xmp or not having , and write or not xmp inside the photo file.

**Comment by pbranly** [comment]
And I even try to write inside the file and having sidecars xmp then delete xmp files . I verified that the files are modified with internal positions 
The issue is just when I don’t want to keep original file . ( that I never do but this should work !)
Phil

**Comment by nemethviktor** [comment]
The "overwrite xmp in file" has to do with the types of tags - there are broadly 3 kinds of tags, iptc, exif and xmp. These are possibly all stored inside the file but generally xmp tags aren't created, not even internally by the camera. So those settings mean that if you enable it, xmp tags will be added inside the photo file. Entirely separately from that you may choose to also create sidecar files. The whole logic has to do with workflow and versioning, which I think you don't use (most people don't)
As said above the unauthorized error is unrelated -> have you set your username and password?

**Comment by pbranly** [comment]
Which user name/ password ? the geonames ones ? sure they are otherwise I would have issues when wanting and keep _original file.
I agree that this option is shared by the exiftool program but it is surprising to have an issue when wanting to prevent the generation of each _original file
Did you try the option on your side ? honestly I never tried with command line. I will later today
Phil
![2022-11-07_09-25](https://user-images.githubusercontent.com/22018509/200262108-71eee645-4fe8-4cfb-8bf6-08f70be16740.png)

**Comment by nemethviktor** [comment]
Yeah that one ;)
I recall having had a look but will do again in the afternoon.

**Comment by nemethviktor** [comment]
I'm still at a loss here. Did a test run as per follows:
1 Installed fresh Windows 10 22H2 FR Home
2 Installed dev version of GTN, set my GeoNames Username/passw
3 Downloaded sample ARW file from https://img.photographyblog.com/reviews/sony_a7s_iii/photos/sony_a7s_iii_01.arw (not my blog, not my site)
4 Modified your GPX files so that one of them lines up time-wise with the image above.
---
5 Set the following for ARW:
- Add XMP In File OFF
- Add XMP Sidecar OFF
- Overwrite Orig OFF
6 Synced GPX + Location via API OK
7 Saved file
8 Observed Settings in nr 5 were applied correctly.
---
9 Reset ARW file with a fresh copy of original
10 Set the following for ARW:
- Add XMP In File OFF
- Add XMP Sidecar ON
- Overwrite Orig OFF
11 Synced GPX + Location via API OK
12 Saved file
13 Observed Settings in nr 10 were applied correctly.
---
14 Reset ARW file with a fresh copy of original
15 Set the following for ARW:
- Add XMP In File OFF
- Add XMP Sidecar ON
- Overwrite Orig ON
16 Synced GPX + Location via API OK
17 Saved file
18 Observed Settings in nr 15 were applied correctly.

I can't find the problem, it works ok for me.

**Comment by pbranly** [comment]
Strange 
I Will do further tests today 
What are specific on my side:
- windows 11 pro very last version
- Installation of GTN with standard option “just for me” (other one is “for everybody” … perhaps English is different but selunderstandable)
- Défaut directory xxxxxxx and when I choose a set of photos by default GTN is under xxxxxx and I go to xxxxxx/tag/Sony/test

phil

**Comment by nemethviktor** [comment]
I'll get that config running and will retest but I'd be surprised if it made any real difference.

I've (just now) updated the install file on the shared folder, I don't think it will make much difference but the app will now clear the local storage of coordinates on each restart. (there is a cache of coords + altitude/toponomy that's stored in case user queries the same coords over and over again then no need to ask the API for that multiple times, that now gets cleared on each restart).

**Comment by pbranly** [comment]
Will use the last software later on … pc is shared with my wife …
I will also try to use that option in command line 
[Utilities](https://exiftool.org/exiftool_pod.html#Utilities)

  -delete_original[!]              Delete "_original" backups
  -restore_original                Restore from "_original" backups
  
But it surprising to get errors only with the -delete_original tag that you surely use for this third option 
Phil

**Comment by nemethviktor** [comment]
https://drive.google.com/file/d/15ptnUIJM3lnepvBL9BUm3NTAinq3kLPH/view?usp=sharing
That's a link to a screenshot video, it's about 10mb and 4 mins long. Normal HD size (a bit wide) so if you're watching on a larger screen it might come across poorly compressed but I didn't poke around much with the screencap settings. 
Basically: Win11 Pro, new install, new everything, works. :) - I even followed your file structure.
If it's not working for you, I'm at a bit of a loss :/

**Comment by pbranly** [comment]
Hi,
with last version 0.6.8346
settings off off off same issue; I have this geonames api error for each photo; i just have to click ok for each photo and at the end, I have what I want !
I have verified the validity of both login and password and even resized it in the settings but the error is still there

In fact I have the issue for all setting configurations. (I dont remember why this morning one was working without issue

Why does it work finally ? what is the role of geonames ?
![2022-11-07_16-22](https://user-images.githubusercontent.com/22018509/200349854-1b016e01-3684-4314-a758-118b50824a7d.png)
![2022-11-07_16-21](https://user-images.githubusercontent.com/22018509/200349873-b99c3c59-f371-4a8d-a004-d46e78867ed9.png)

**Comment by nemethviktor** [comment]
Geonames is responsible for associating coordinates with places. (ie getting the actual information that the coordinate x/y is in London or Rome or whereever).
I can't debug it for you because it works for me. 
If you feel adventurous enough though you can try something. 
- download & install https://download.sqlitebrowser.org/DB.Browser.for.SQLite-3.12.2-win64.msi sqlitebrowser
- open sqlitebrowswer and then in it open the file C:\Users\YOURUSERNAME\AppData\Roaming\GeoTagNinja\database.sqlite 
- go to Browse Data
- pick the Settings table
- in the filter for the SettingID type in "geo" (or just find the value on the screenshot)
- check that the username and password is what you'd expect to find.
- let me know pls

![image](https://user-images.githubusercontent.com/58767235/200352420-dc94215f-7fd2-48f8-a2a1-56114ba7c506.png)
![image](https://user-images.githubusercontent.com/58767235/200352527-9319a675-2a6c-4b84-8dbe-9b50dc0c1047.png)
![image](https://user-images.githubusercontent.com/58767235/200352846-67f92bca-aa22-47af-a044-31283efa058c.png)

**Comment by nemethviktor** [comment]
Bit of a +1 but in your browser, try:
http://api.geonames.org/findNearbyPlaceNameJSON?formatted=true&lat=47.3&lng=9&username=YOURUSERNAME&password=YOURPASSWORD
where the username and pwd are what you have in the sqlite database. 

![image](https://user-images.githubusercontent.com/58767235/200361476-a74536ab-b9a9-407d-8863-e75e1da03ac9.png)

**Comment by pbranly** [comment]
It says 

{"status": {
  "message": "invalid user",
  "value": 10
}}
I use  as username the mail that works for login in geonames 

and if I use username given by gzonames

{"status": {
  "message": "user account not enabled to use the free webservice. Please enable it on your account page: https://www.geonames.org/manageaccount ",
  "value": 10
}}

!!!

**Comment by pbranly** [comment]
I have activated the free web service ! 
quite hidden menu ….

not easy from my iphone as pc is not available at present time 

answer is now :
{"geonames": [{
  "adminCode1": "SG",
  "lng": "9.01488",
  "distance": "1.1379",
  "geonameId": 7910950,
  "toponymName": "Chrüzegg",
  "countryId": "2658434",
  "fcl": "P",
  "population": 0,
  "countryCode": "CH",
  "name": "Chrüzegg",
  "fclName": "city, village,...",
  "adminCodes1": {"ISO3166_2": "SG"},
  "countryName": "Switzerland",
  "fcodeName": "section of populated place",
  "adminName1": "Saint Gallen",
  "lat": "47.2985",
  "fcode": "PPLX"
}]}

so this should work now 
Thanks 
Phil

**Comment by nemethviktor** [comment]
Okies, that sounds promising. 
If it still doesn't work, let me know if the username that you see in the GTN settings is identical (or not) to the string you see in the sqlite database. It should be the same because it's a normal string (rather than anything related to numbers, which could possibly be a problem re: commas in decimals and whatnots)
Basically the short version is that if the username and password in sqlite is what you would expect it to be _and_ the API call in the browser works with that user&pass combination then GTN should work too.

**Comment by pbranly** [comment]
fantastic ! it works
I have to test everything now
good job

![2022-11-08_08-39](https://user-images.githubusercontent.com/22018509/200503998-de7b9306-6832-468f-b594-be9777c3bd12.png)
![2022-11-08_08-42](https://user-images.githubusercontent.com/22018509/200504001-14fbc123-8c4d-4c6a-90b1-9c3471fbe108.png)
![2022-11-08_08-40](https://user-images.githubusercontent.com/22018509/200504004-b3c25b8a-ca8d-48f0-a775-0d5659e27240.png)

**Comment by nemethviktor** [comment]
Ok, same link as above (https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link) patched a few things:
- when user presses OK it will change to a "pls wait" button
- there was a bug that if user parsed the same image file more than once it'd delete the city/etc data but not refresh it.
- other small things

**Comment by pbranly** [comment]
I had a notification that a new version of exiftool is available but link gave this error:
![2022-11-08_16-18](https://user-images.githubusercontent.com/22018509/200608288-7d9a2ec9-af01-46cd-8dbe-c8ab7d51de6e.png)
nevertheless the link https://exiftool.org/exiftool-12.50.zip works correctly when used under firefox

For the french translation I would prefer:
Ajouter/modifier positions XMP dans le fichier  
Créer/remplacer tags dans un fichier XMP séparé
Ne pas conserver de sauvegarde xxxx_original

And : when importation of the position file is  finished, positions are seen in the file details on the left but not yet on the map. It is necessary to rehighlight all the files for seing the results. Could it be in real time ?

Isn't it yet the time to deploy officially this very good program and find other beta testers ?
It is now very very close to the geosetter versiondont you think ?

congratulations
Philippe

**Comment by nemethviktor** [comment]
Hi, 

Thanks for the updated translations ;)
I'll patch the issue re: 12.50. - the issue there is that it's taken as a numeric value and C# thinks that 12.50 really means 12.5 - I'll work around it. 

Re showing updates on the map.: the map only triggers when the listview (grid) selection changes. I've now lost track of the various updates but one of the things upcoming will be a faster handling of Control + A (select All) as it's pretty slow in the current version, possibly even the one you're testing.

**Comment by nemethviktor** [comment]
Actually if you still feel like playing around with changes, I've updated just now the one on google drive. It has your updated translations and bits and bobs of new code.

**Comment by pbranly** [comment]
![2022-11-09_07-21](https://user-images.githubusercontent.com/22018509/200755965-459a24e3-078c-41c2-b51d-0f89ed101af4.png)
![2022-11-09_07-28](https://user-images.githubusercontent.com/22018509/200755971-5af984f1-d286-4fc1-a237-809230b89e84.png)
![2022-11-09_07-24](https://user-images.githubusercontent.com/22018509/200755974-6116c50c-847e-4729-9cd7-64a7ecadf76e.png)
very quick test this early morning
Phil

**Comment by nemethviktor** [comment]
Hi, 
I'll have a look at resizing that Form but yes the text is a bit lenghty.
The other 2 Qs:
- I don't know why it's not showing in the first screenshot as I don't have your files/settings...What's in the Report, does it recognise the location? Alternatively if you don't mind re-uploading your test files someplace (just the images, I think I have the GPX files) I can have a look.
- The "why they do show" is a bit trickier. It's because I think you asked ;) -- a user did anyway. Basically originally when there were no valid coordinates the map would then default to coords 0.0/0.0 but that made it difficult to tag series of images one by one so it's been decided that the map would only refresh if the `SelectedItem` has valid coordinates, which in case of your screenshot is `False` thus no refresh.

**Comment by pbranly** [comment]
I don't know why it's not showing in the first screenshot as I don't have your files/settings...What's in the Report, does it recognise the location? Alternatively if you don't mind re-uploading your test files someplace (just the images, I think I have the GPX files) I can have a look.

---------> this was not the issue; my gpx files are such that they are missing for some photos with the time frames set in the GTN. So after uploading positions, some positions are missing. I have then 2 solutions : 
- increase the time frame until it finds position but they will be wrong (could be enough in some cases)
- choose one or several photo where positions are missing, tag a position on the map and find a way to send this position to the selected photo(s). 
- This is what I dont find or dont find obvious

    The "why they do show" is a bit trickier. It's because I think you asked ;) -- a user did anyway. Basically originally when there were no valid coordinates the map would then default to coords 0.0/0.0 but that made it difficult to tag series of images one by one so it's been decided that the map would only refresh if the SelectedItem has valid coordinates, which in case of your screenshot is False thus no refresh.

----> understood 

Phil

**Comment by pbranly** [comment]
understood
![2022-11-09_12-06](https://user-images.githubusercontent.com/22018509/200814452-4b7966b8-af79-4e16-9bcb-5007a80bec46.png)

**Comment by pbranly** [comment]
in english it is better
could you do it bigger ? after all this is one of the more important feature of the program
![2022-11-09_12-08](https://user-images.githubusercontent.com/22018509/200815079-11ad0cc9-3c8e-477d-903b-047ed5959291.png)

**Comment by nemethviktor** [comment]
_increase the time frame until it finds position but they will be wrong (could be enough in some cases)_
That's one for the user to pick I'm afraid.

_choose one or several photo where positions are missing, tag a position on the map and find a way to send this position to the selected photo(s)._
There is a copypaste function already you know - I think that's generally what you're after. 

In the screenshot with "test position i want", i can't see the coordinates on the grid but i'm assuming that  those coordinates are interpolated numbers rather than "documented ones" - if so then it's a function of how Exiftool generates the interpolation.  GTN doesn't do calculations, exiftool does. 

Button size: noted. I'm working on (mostly done actually) on a patch that will make elements resizable (the main ones, anyway), I'll add it in while there.

**Comment by nemethviktor** [comment]
Actually, usual g-drive path, uploaded a new version if you feel like experimenting.

**Comment by pbranly** [comment]
french menu "Loc au fichier" ... mmm ! could you put something like "Copie positions dans le(s) fichier(s) selectionné(s)
![2022-11-09_13-10](https://user-images.githubusercontent.com/22018509/200830663-c4f1bbcd-d6b0-4e03-b7dd-3ac7d3c9b7b4.png)
+ other remark
Phil

**Comment by nemethviktor** [comment]
Can you make that a lot shorter please ;)
Alternatively I can replace it with an icon and have a tooltip that can be
long

This message has been brought to you by my Huawei P30 Pro and myself. Any
typos blame the phone.

**Comment by pbranly** [comment]
I am lost with the tests !
I choose a very small extrapolation duration when uploading positions in order to have photos with and without positions.
Then I added a very different location in one photo
then save

but after stopping ans starting application and using same photos, correct locations in the previous session were missing

I have to stop a bit the tests ! and perhaps choose new virgin photos !!!

and I got a windows error (second time)

Phil


![2022-11-09_13-21](https://user-images.githubusercontent.com/22018509/200831974-9a531363-48c6-4117-ba03-f1e7c2fc35ae.png)
![2022-11-09_13-22](https://user-images.githubusercontent.com/22018509/200831987-9c19b680-83ca-4eea-b57b-10dfca83e96e.png)
![2022-11-09_13-23](https://user-images.githubusercontent.com/22018509/200831997-b21431ab-e8ed-45c2-bde3-a4b36639d128.png)

**Comment by pbranly** [comment]
![2022-11-09_13-14](https://user-images.githubusercontent.com/22018509/200832120-9ee5aec8-4f3b-4366-b363-9dfc45408505.png)

**Comment by pbranly** [comment]
this is the message in geosetter (right clic)
![2022-11-09_13-58](https://user-images.githubusercontent.com/22018509/200837151-77c7bfc0-ddde-4b6d-92fb-a08000365513.png)

**Comment by nemethviktor** [comment]
Thing is, I don't know how GS did/does its things. It's not using exiftool (ET) but the guy either coded most of it himself or did some alternative magic, but since it's not an opensource project I can't quite guesswork it. GTN uses ET to do just about everything so if ET doesn't interpolate the values then there's nothing I can do about it/them. 
As I wrote at some point above I don't have the code to standardise and parse a lot of Track-file-formats and it'd not be beneficial for me to try and reinvent the wheel on that one if ET is already doing a fine job on it.

If you find a way to coerce ET to get the interpolation, I can look into if it's being picked up by GTN.

`exiftool -geotag=2022-09-07_11-53-42.gpx -geotag=2022-09-07_11-53-42.gpx "-geotime<${DateTimeOriginal#}+02:00" sony_a7s_iii_01.arw -api GeoMaxIntSecs=1800 -api GeoMaxExtSecs=1800`

...where for each of the gpx files you need a `-geotag=2022-09-07_11-53-42.gpx` (obvs amend) and the `+02:00` is something you might need to change.

**Comment by nemethviktor** [comment]
Appreciating you're not in front of a PC at the moment but...If you expect something is a bug I can only debug if I have the precise settings you used. If you modify 13 files and it only saves 7 of them then I'll need the 13 files, all the GPX files and the relevant settings used for the import so I can reconstruct it on my version and debug ;) - as always, if you'd prefer sending things in private, that's ok too.

**Comment by nemethviktor** [comment]
> this is the message in geosetter (right clic) ![2022-11-09_13-58](https://user-images.githubusercontent.com/22018509/200837151-77c7bfc0-ddde-4b6d-92fb-a08000365513.png)

![image](https://user-images.githubusercontent.com/58767235/200879405-7f615c17-4d50-44e1-807c-c3247f53bec9.png)
Upcoming change fyi.

**Comment by pbranly** [comment]
Hi
I sent you a directory with a set of photos that shows the issue 
After further tests, it seems that it is linked with the option to write xmp positions inside the file .
With the option to write sidecar xmp only, the issue seems to be absent.
I say seems because even with « only xmp » there was one file without positions only
And I tried as well to close then open GTN and import photo and the number of photos without positons changed 
Phil

**Comment by nemethviktor** [comment]
I'll have a look later today if I get around to it - work is a bit busier
this second half of the week now.
Thanks for the files (not downloaded them yet so leave them on please for
now) + the details as well :)

This message has been brought to you by my Huawei P30 Pro and myself. Any
typos blame the phone.

**Comment by nemethviktor** [comment]
Hopefully all good now - see new release. :)
