### ISSUE TITLE
Images suffix "jpeg" cannot be displayed in preview (but jpg does work)

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#17]
### Setting
- Latest greatest provided in this issue: https://github.com/nemethviktor/GeoTagNinja/issues/15.
- Running on a German Win10 machine.

### Error
Images with suffix "jpeg" are not displayed in preview. No error is shown - the preview is just blank.

### Workaround
Rename jpeg to jpg solves the issue :)

**Comment by nemethviktor** [comment]
Noted, will have a look :)

**Comment by nemethviktor** [comment]
I can't seem to repro this - there is no reason why it shouldn't work, the code logic is that if it's a JPG then it should just take the file as-is for "preview", otherwise (even if jpeg...admittedly I didn't think about it) extract a preview. 
Any chance you can share the file in question?

**Comment by nemethviktor** [comment]
![image](https://user-images.githubusercontent.com/58767235/203419954-55d2db5e-3f25-4e73-aeb0-2098d1239fcf.png)
![image](https://user-images.githubusercontent.com/58767235/203419990-8cedd26b-bca1-4266-9156-41a0d722e65c.png)

(the 2nd one is a "jpeg")

**Comment by Urmel** [comment]
Hi @nemethviktor,
thanks a lot for the super quick reply!
Yes! I can provide such an image... attached.
BR
Alex
![image-20222108-103550-6](https://user-images.githubusercontent.com/1786902/203433241-7e042bd3-4a51-4634-beec-24d74ccb0593.jpeg)

**Comment by nemethviktor** [comment]
Your file is corrupted/there are no previews in it. (not entirely sure which)
![image](https://user-images.githubusercontent.com/58767235/203435138-d089d0bd-2dfe-4e83-b9dd-071b96654150.png)

Basically exifTool can't detect any embedded preview-style data in the file, which is why it's not extracting.
I've done a quick googling on that IPTCDigest thing but no relevant avail so far.
The reason why it works for JPG but not JPEG is bcs the current logic is that for JPGs it uses Windows' own thing, so clearly your file isn't useless but for some reason ET can't parse it properly.

Anyway, I've updated the code (the build will be the same as earlier because build number is just the number of days since 1/1/2000 -> same link as before -> https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link

This only fixes this particular issue (I saw your latest comment on the crashes, I'll have a look at that tomorrow, zombie now.)

**Comment by Urmel** [comment]
Hi @nemethviktor,

I tested using (can we make that text copy-able?):
![grafik](https://user-images.githubusercontent.com/1786902/203866694-2d717317-86fa-4a09-bd5f-738e2e682e21.png)

I did the usual cursoring up and down:
- Cursoring up and down in the "regular" files (the ones that were already working - likely had a working preview graphic) was as slow as before
- Cursoring through the files that were not working before went "super fast" - I'm not able to build up a relevant delay between stoping cursoring versus the last screen refresh. In contrast to "previously working images", where there is multi second delay after doing some wild cursoring.

**So for me, this fix solves the problem!**

Thank you!!
