### ISSUE TITLE
Metadata writes

### ISSUE THREAD

**Issue by TWCunningham** [nemethviktor/GeoTagNinja#5]
I'm not real clear on how the metadata gets written to the file.  I can copy and paste geodata from one picture to the next, and when I move to another photo the pasted data turns red.  Then I do File->Save All and the red turns to black.  But when I attempt to verify the coordinates in a program like digiKam, the map reports no geolocation data found.  However, if I push "Loc to File" under the map, the data again turns red and if I do File->Save All the coordinates do register in digiKam (e.g. I get a map with the correct location).  I would think that the File->Save All does the same thing in both instances.  I'm assuming that Save All only updates modified photos, correct?  Note that the text data turns red as modified only after moving to another line in the photo list.

**Comment by nemethviktor** [comment]
Okay, a few things. Not sure you're aware but there used to be (kinda still exists) an app called GeoSetter. I think the guy who wrote it has passed because his last ever blogpost was years ago complaining of poor health and no updates ever since. If you have a look you'll find it looks a lot like this app (I wrote this one from zero but obviously the basis for the logic here was what I saw there as a user.). So the red/black is a reminiscent of behaviour from that one. 
Red means there is data to be written and black means there is no data to be written (that may be achieved by data having already been written, so it goes from black (default) to red (changes queued) to black (changes written, nothing in queue).
Data rows do turn red as soon as you're out of the edit field because it pushes the change into the main listview (the grid you see) - I but the actively selected row always appears black. You can check this by making a change, moving away from the row (turns red), moving back to it  (appears black) - I think it's a default behaviour of that Control.
Save All only saves modified photos indeed. 
I'll have a look at digiKam, I haven't used it - maybe I can catch where the issue is but in theory the "loc to file" is identical to the "edit" process. Basically it queues up certain tags and then when you Save they get written.

**Comment by TWCunningham** [comment]
Cool, good explanation.  Yeah, I watched your video and some things got clearer.  Oh yes, I know GeoSetter very well, that's what I used to use all the time, but as you point out it hasn't been updated and is very hard to use now.  I've been using GeoTag (Java), which is kinda clunky but fine, does the job, until it doesn't, which is why I came upon your app.  I think what GeoTag is running into is exiftool makernote errors which is causing it not to write updates, even though I don't care about makernote errors or warnings even.  Now I think I can get your tool to work for me with those "problem" photos (Olympus TG-5 versus my standard Sony RX100-VI).  And thanks for making the effort to provide an update for GeoSetter, much appreciated!

**Comment by TWCunningham** [comment]
Forgot to mention, that would be very sad if Friedemann (GeoSetter) passed away.  Such a great program!

**Comment by nemethviktor** [comment]
Not explicitly sure if he passed but considering his last post's content and old date plus the total lack of activity from him in forums and bug reports and basically everything I'd assume there is something beyond "not feeling like updating it" :/
Btw if you have issues w specific files and don't mind sharing the photo (file) I can try to debug.

**Comment by StarGeekSpaceNerd** [comment]
For what it's worth, if you go to the [Geosetter about page](https://geosetter.de/en/about-en/) and check the social media links, there is activity there.  FB has a August 7th post, for example.

**Comment by nemethviktor** [comment]
Glad he's okay then ;) 
Still, now there's this project too. For me it's a coding exercise and if the community uses it am all the happier.
