### ISSUE TITLE
Copy-Paste Geoinformation across different folders

### ISSUE THREAD

**Issue by lintujuh** [nemethviktor/GeoTagNinja#54]
**Is your feature request related to a problem? Please describe.**
Copy-Paste (Ctrl-Shift-C/Ctrl-Shift-V) doesn't work across folders.

I took pictures in the same place in two different days. I had created a GPX file during the first day, but didn't do that on the second day. I import my images into a folder structure based on dates, and I couldn't copy-paste the location from the first day images to the second day images. Only workaround I had was to create a favorite on that place, and use it, but I think it is an overkill for random locations.

**Describe the solution you'd like**
Copy-Paste works across folders, and don't forget the information, when the folder is changed.

**Describe alternatives you've considered**
–

**Comment by nemethviktor** [comment]
That's actually a bug - it should work but indeed it doesn't - I'll look into it this week.

**Comment by nemethviktor** [comment]
Try the current dev version link pls? -> https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link

Should work ok/faster I think -- change affect copy/paste in the main Form (ie not in Edit).

**Comment by lintujuh** [comment]
Hi, and thank you for your quick fixes.

Copy-Paste woks now, the only minor issue is, that when I paste, the
coordinates (lat, long, alt) are not selected in the paste dialog. I have
to manually select them.

Ignoring the reverse geolocation works also fine, tested that also.

-Juha

**Comment by nemethviktor** [comment]
There's some logic to attempt to auto-select what has changed and those would be selected initially - the updated version uses a simplified version of that logic, hence faster but probably a bit more flawed (e.g. in the updated version you can't paste "shifts" from within the folder but only within Edit because shifts are not exif tags and the new one only looks for tags). 

I will have to rewrite the paste process a bit better but there's some underlying effort going on to restructure how the code works in general because at the moment the base logic is a little slow and depending on how that goes I'd be a bit tempted to wait on redoing paste.

**Comment by lintujuh** [comment]
As the issue as such is fixed and all code can always be improved, I'm happy with the fix.
