### ISSUE TITLE
Use EXIFTool Available to also Generate ImagePreviews

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#55]
As discussed in https://github.com/nemethviktor/GeoTagNinja/discussions/40, image previews should also be called by the EXIFTool stay_open version. Basically most pics are likely to require a generated preview so firing up ET each time when we have this already working seems like a no-brainer for switch.

- [ ] Check how this can be done with stay_open
- [ ] Adapt logic to use the stay_open Wrapper

**Comment by nemethviktor** [comment]
@Urmel ,

Hmmmm so I've been doing a little (not a lot tbh) digging and found a half solution. 
Half because the image creation works but the rest of the data doesn't get loaded 🤦  [rest = exif]

If we change 
`const string c_arguments = @"-stay_open 1 -@ - -common_args -api ""Filter=s/\r|\n/ /g "" -a -s -s -struct -G -ee -charset UTF8 -charset filename=utf8 -args";` 

to

`const char SDoubleQuote = '"';`
`string c_arguments = @"-stay_open 1 -@ - -common_args -api ""Filter=s/\r|\n/ /g "" -a -s -s -struct -G -ee -charset UTF8 -charset filename=utf8 -b -preview:GTNPreview -w! " + SDoubleQuote + FrmMainApp.UserDataFolderPath + @"\%F.jpg" + SDoubleQuote + " -args";` (not `const`) 

the images get generated.

There is however one relatively major logical flaw here. Notwithstanding that the exif doesn't get loaded this would run on each file on folder entry, which is a bit wasteful because there could be 1000s of files and that could take a lot of time.
My understanding is that while the current logic calls the `GetProperties` on each file (hence the image generation taking place for each file) this can't be done on a click-only basis because the `arguments` are per `process`, not per `method`. (ie we even if we added a `GetPreview` it couldn't be commanded to use a different set of args. 
I'm thinking the only way around this would be to call a _second_ exiftoolwrapper where the args would be specific to the preview creation?

**Comment by Urmel** [comment]
Hi @nemethviktor,

some thoughts on this....

It might generally make sense to decouple image generation and EXIF tag readout. At least under the premise that image generation takes much more time.

This being said, we could go two ways

Common EXIFWrapper
- Use locks, queues or alike to force non-concurrent execution of read properties / image method
- We need to decide whether we block requests waiting or/and we cancel requests (reject) them (or do that after some time).

Separate EXIFWrapper
- Still relevant to ensure that only one call is run in parallel - which might already be the case depending on how "getPreviewImage" is called. If not, see above...
- An instance of the EXIF Tool seems to take around 30-45 MB of RAM (which seems acceptable for having multiple of these)

I get your point with the arguments being different and the issue with the const. From a first glimpse at the docu of execute nevertheless, it could be possible to pass the differentiating args per call and the common args in the const. Something like this:
![grafik](https://user-images.githubusercontent.com/1786902/213712597-5f237ab4-a625-4d99-91b8-34bb57a9fcf7.png)

That being said, my gut feeling would as well be that the second instance of the wrapper is just the more straightforward solution. It might also be the one with less effort, as we otherwise would need to ensure that tag calls and image calls are not comming in concurrently.

We might run into issues when we have also concurrent writes (user edits multiple items, writing starts, while this is running user clicks on a image for which a preview is generated and in parallel the metadata updated).

**Comment by nemethviktor** [comment]
hi @Urmel ,

I'm with you on the idea of separate, we can always test it out.

On a rather unrelated note your version is missing a merge from dev, I've changed how the image preview gets created (`internal static async Task GenericCreateImagePreview` in particular because the existing version put a blocker on jpg files.) -- not a biggie, i'll merge it when i get around to it, but fyi anyway)

**Comment by Urmel** [comment]
Hi @nemethviktor,

I've looked a bit into image preview generation - I think it can be implemented as we though, but have some questions...

P.S.: you could assign this ticket to me if you like

### Preview Gen called twiced
The preview generation is called twice when clicking on a list item - once inside LvwItemClickNavigate (when its the last item) and the further down in lvw_HandleSelectionChange.

--> Can we remove the first one (inside LvwItemClickNavigate)?

```
    private async Task lvw_HandleSelectionChange()
    {
...
            await HelperStatic.LvwItemClickNavigate();
...
                    await HelperStatic.GenericCreateImagePreview(
                        fileNameWithPath: fileNameWithPath, initiator: "FrmMainApp");
```

### GTNPreview type
I understand that we look for the preview type called "GTNPreview" in the files...

This is not always included in the files - like so:
```
PS C:\Shares\z.Local\Programming\GeoTagNinja\bin\Debug\Resources> .\exiftool.exe "C:\Shares\Media\_in_Arbeit\Bild+Video\3 - JustGeoMissing\2021_11_17 Zoo\20211117_114527.jpg" -preview:all
Thumbnail Image                 : (Binary data 54688 bytes, use -b option to extract)
PS C:\Shares\z.Local\Programming\GeoTagNinja\bin\Debug\Resources> .\exiftool.exe "C:\Shares\Media\_in_Arbeit\Bild+Video\3 - JustGeoMissing\2021_11_17 Zoo\20211117_114527.jpg" -preview:GTNPreview -b
PS C:\Shares\z.Local\Programming\GeoTagNinja\bin\Debug\Resources> .\exiftool.exe -charset UTF8 -charset filename=utf8 -b -preview:GTNPreview -w! "C:\Shares\z.Local\%F.jpg" "C:\Shares\Media\_in_Arbeit\Bild+Video\3 - JustGeoMissing\2021_11_17 Zoo\20211117_114527.jpg"
    0 output files created
PS C:\Shares\z.Local\Programming\GeoTagNinja\bin\Debug\Resources>
```
... which then leads to reading in the image itself.

But the title "GTNPreview" sounds rather individual for GeoTagNinja... how do previews get into the file?


### Preview Caching
It seems that we can grab the image preview binary data directly from the wrapper:
![grafik](https://user-images.githubusercontent.com/1786902/216761541-93210a93-04b2-480f-923a-8a4db9195c84.png)

We could then attach the img object to the directory elements (when reading the full image, we would need to make sure to scale it down to an appropriate size). That would get rid of reading in the files again, thus improving performance. We would clean out the images on every directory change - which essentially is the same that we do by wiping the tmp files on directory change.

Pro:
* Performance
* Less temporary files

Con:
* Could result in increased mem consumption - esp. when having large directories (~120kB/file --> 1K image files clicked ~120MB RAM)

If the reduced file I/O seems beneficial, but we need to ensure a mem limit on previews, we could remove them from memory (FIFO queue like only keeping ~100 previews).

**Comment by nemethviktor** [comment]
I'll have a look at the redundant calling next week.
The reason why you can't find GTNPreview is because it doesn't exist. Not per se anyway. If you look in the .ExifTool_config file there is some perl code in it related to this. Basically what it does is that it instructs exifTool to look for various types of embedded previews and extract (and rotate) the first one found. 
That however only gets called for non-jpg files. If Windows can (on its own) decipher the preview (which it's only capable for certain file formats, jpg being one of them) then it does it on its own. Otherwise as a fallback it gets ET to pull the "GTNPreview".
If you think that we can use the data available in the DE/wrapper and stick it into the memory, it sounds good to me and feel free to experiment. I further think that a couple hundred MBs of RAM used shouldn't really be an issue nowadays. One'd hope that if people try to work with RAW files they have computers more powerful than a Celeron with 2 gigs. :)

**Comment by Urmel** [comment]
... topic continued in PR https://github.com/nemethviktor/GeoTagNinja/pull/69 ...

**Comment by nemethviktor** [comment]
I think this has been sorted (?) -- closing but feel free to reopen.
