### ISSUE TITLE
GTN thinks it wrote changes even if write failed (+ localization issue)

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#58]
Failing to write results in loosing the changes, because GTN thinks that it already wrote them.

### To Reproduce

1. Start editing a file that previously has no geo info:
![grafik](https://user-images.githubusercontent.com/1786902/213818123-6647bbf9-a1e8-487c-bf87-ec5edf3d6231.png)

2. Using the map, assign a long/lat to it
![grafik](https://user-images.githubusercontent.com/1786902/213818205-5ec6e9f2-7e7b-40f8-b0a3-a5c3e968fff6.png)

3. Save (which must fail in order to reproduce the issue, e.g. by setting the file to write protected)
![grafik](https://user-images.githubusercontent.com/1786902/213818336-c99a804a-d426-4efa-afff-9b875185cc27.png)

4. Although the data is not saved, it is marked as saved and the write-queue is emptied:
![grafik](https://user-images.githubusercontent.com/1786902/213818465-04b2821b-cc94-4f7f-ac00-e9bd442f1608.png)

**Second issue: localization**

- As can be seen in above screenshots, localizations of 3 error dialogs are missing

### Expected behavior
The changes that failed to get persisted still remain as changed.

### Desktop (please complete the following information):
Used GTN version: https://github.com/nemethviktor/GeoTagNinja/pull/52

**Comment by nemethviktor** [comment]
Exiftool doesn't quite have a good way of feeding back a write-fail in a simple way we can pick up (not the least because we're just using `cmd` to do everything so even if it did we wouldn't have the interface). 
It can throw a lot of various messages so the assumption for a write-fail would have to be that it's explicitly containing "error" and "writing". 

Atm we have a `FrmMainApp.DtFileDataToWriteStage3ReadyToWrite.Rows.Clear();` at the end of the save process, which clears the write-queue. This could be moved/modified to do a `delete from dt3 where filename = filename` (i know it has a different col name) if there is _no_ write-error message I guess, tho' it'd be a bit slower as deleting from DT takes a bit of time.

**Comment by nemethviktor** [comment]
Re: localisation: actually the headers of messages aren't localised at all. I should add in something to do those.

**Comment by nemethviktor** [comment]
Okay the best guess here is --> https://github.com/exiftool/exiftool/blob/66d3e6f6e5e80b50e30b1e53b153176dea73ec15/exiftool#L1899

ET doesn't seem to have localisation and so the write-error just seems to be a `files weren't updated due to errors` msg -- basically if the line throws that error we can deem it failed.
I'll have a look soon.

**Comment by Urmel** [comment]
Hi @nemethviktor,
I see that you had success in implementing the write-error behavior.
Do you see any open issues left in this ticket?
Thanks!!!

**Comment by nemethviktor** [comment]
Nah, I'll close it, if there's anything left you can always reopen or open a new one ;)
