### ISSUE TITLE
Lat/long for photos without GPS data

### ISSUE THREAD

**Issue by PeterBDa** [nemethviktor/GeoTagNinja#7]
This looks like a worthy replacement for GeoSetter. It would be nice if, instead of centering on 0°N 0°E, when adding GPS data to a series of photos without it, the map would default to either a usergiver location or to the location of the last photo treated.

**Comment by nemethviktor** [comment]
I think that's more of a feature than a bug. 
Appreciating what you're asking about is not this but on application-open we're already defaulting to the last photo's location.
If there is no geodata I think it would be misleading for people to be shown the last location because they might not notice that it's basically "false" data. A 0/0 is hard to miss. Users can generally copypaste values from chosen other pics if they want.
If it'd make things easier I can code a user-choice setting into Settings to either default to 0/0 or last photo or something. (?)

**Comment by PeterBDa** [comment]
Thank you for your quick reply. Just to be clear: I am only talking about centering the map when going to a photo without location, not entering any location data into the photo itself. I have just added location data to a series of 40 photos and it was a bit frustrating to, every time, have to zoom right out from the middle of the Atlantic Ocean, then translate and zoom back in to find my (small) country, then my town and finally my street. It would have been a lot easier if, when going to the next photo, the map was still in (about) the same location. Nevertheless this is definitely just a 'nice to have'; I shall continue to use your application with pleasure (and relief!)

**Comment by nemethviktor** [comment]
That's ok I'll add in a setting for it one of these days soon :)

**Comment by PeterBDa** [comment]
Fantastic!

**Comment by nemethviktor** [comment]
Ok try this one -> https://github.com/nemethviktor/GeoTagNinja/releases/download/v0.5.8304/GeoTagNinja_Setup.msi

**Comment by PeterBDa** [comment]
Yes, that is exactly how I like to use it. Very many thanks (and good luck with this project)

**Comment by nemethviktor** [comment]
Welcome - any other requests, shout. :)
ps. thanks for paypal ;)
