### ISSUE TITLE
Map changes zoom level when selecting a new image

### ISSUE THREAD

**Issue by lintujuh** [nemethviktor/GeoTagNinja#70]
**Describe the bug**
When I change the image the map resets it's zoom to the original, and doesn't keep the zoom level previously selected.

**To Reproduce**
1. Open a folder
2. Select an image
3. Zoom close to the location
4. Select another image
5. The zoom level reverts to the original

**Expected behavior**
The selected zoom level would be respected.

**Screenshots**
–

**Desktop (please complete the following information):**
 - OS: Win11
 - Version: 0.7.8421

**Additional context**
The problems started when I zoomed and panned from Finland to Lisbon, when I tried to geotag my vacation photos.

I tried to close the program and restart it – it didn't help.

**Comment by nemethviktor** [comment]
Hi, 

I'm not sure this is fixable as such. The map itself is very independent of the app, it's a `leaflet`-based add-in -> https://leafletjs.com/

Here's the issue: when the user clicks on an image the app tries to estimate the relevant area for the image on the map and then puts the image on the map with the coordinates +/- some area. This is so that 1) we are not showing the whole globe literally and 2) we are showing the area where the image coordinates are. In reality this is particularly important when the user selects more than 1 image so that the markers are all showing properly on the map in a way that's kinda "neither too small nor too big".

From a coding logic the way this works is that when the user clicks on any number of images **the map is reset**, then for each of the coordinate pairs in the clicked-image-list we record those coordinates someplace and then calculate the extremes of the coordinates to form an area to show. This is largely because if the user was to unselect one image out of the possibly many selected it's a lot easier to redraw the whole thing than to attempt to find a marker on the map (reasoning being is that markers are not named entities and if user has more than 1 selected then it becomes impossible to "undo" one particular marker)

So when user select a _different_ image, even one with identical coordinates to the previous the area box coordinates that get sent to the map are reset and the marker for the image gets put on the map. 

Admittedly at the moment I'm not sure how to _read_ the zoom level from the map without it being clicked anywhere, but that's relatively irrelevant in the big scheme of things because in `map.html` the `fitBounds` code logic defines where to point, which as per [documentation](https://leafletjs.com/reference.html#fitbounds-options) comes only with the `maxZoom` option, which is already being used so a zoom-per-se can't be enforced (and would not be possible either as per above explanation).

**Comment by lintujuh** [comment]
Just guessing, could this be depending on the coordinates. I'm trying to geotag images in Lisbon, ~9 deg West, so could the negative longitude cause issues.

**Comment by nemethviktor** [comment]
The zoom always resets regardless of East or West orientation because when you click on 1 or more image the app calculates a coordinate box/area to show all of the coordinate markers on the map and that sets the view.
You can try the Development version as I did poke around with negative coordinates in it a while ago (in particular regarding showing them on the map) tho I think that change is already in the Main branch too.

**Comment by lintujuh** [comment]
The development version I downloaded from the Google Drive works correctly.
