### ISSUE TITLE
Application fails to process full gpx file to all images

### ISSUE THREAD

**Issue by lintujuh** [nemethviktor/GeoTagNinja#78]
**Describe the bug**
I tried to import a gpx file to 173 images in a folder, but GeoTag Ninja fails silently. The import terminates quickly, and when looking at the import report it is empty. If I import the file in pieces, i.e. select a subset of the images (roughly half), the import completes normally for all parts.

**To Reproduce**
1. Open a folder with very large number of images (170+)
2. Import a gpx file covering all the images
3. See error

**Expected behavior**
All images are tagged without issues, or if there are technical limitations, a clear message showing the error and asking to do the task in pieces.

**Desktop (please complete the following information):**
 - OS: Win11 Enterprise 22H2
 - Language/Culture: en-FI

**Additional context**
GPX file I tired to import.
[2023-03-03.zip](https://github.com/nemethviktor/GeoTagNinja/files/10978814/2023-03-03.zip)

**Comment by nemethviktor** [comment]
Ok, so this is actually something I should have kinda thought about. 
The GPX parse is a bit of a pariah in the code for a variety of reasons but most importantly because unlike the rest of the code, which uses an arguments-file that is created on the fly to interact with ExifTool, this part uses a direct-command execution such as
`exiftool  -charset utf8 -charset filename=utf8 -charset photoshop=utf8 -charset exif=utf8 -charset iptc=utf8  -geotag="D:\temp3\2023-02-28.gpx" "-geotime<${DateTimeOriginal#}+00:00" -api GeoMaxIntSecs=1800 -api GeoMaxExtSecs=1800 "**D:\temp3\_2280104.ORF**" -v2  -srcfile "C:\Users\nemet\AppData\Roaming\GeoTagNinja\tmpLocFiles\%F.xmp"` to do its magic. Observe the file name showing. If there were two files, they'd both show. If there are 170, they all show.
The problem is that CMD commands have a hard limit of ~8000ish characters and if the user is parsing a large number of files then the 8k limit is hit and the whole thing fails. A workaround here that I can do is to just parse the whole folder such as 
`exiftool  -charset utf8 -charset filename=utf8 -charset photoshop=utf8 -charset exif=utf8 -charset iptc=utf8  -geotag="D:\temp3\2023-02-28.gpx" "-geotime<${DateTimeOriginal#}+00:00" -api GeoMaxIntSecs=1800 -api GeoMaxExtSecs=1800 "**D:\temp3**" -v2  -srcfile "C:\Users\nemet\AppData\Roaming\GeoTagNinja\tmpLocFiles\%F.xmp"` and then do something in the code further down the line to only keep information for the files selected. An obvious disadvantage will be the performance hit of having to do the whole folder regardless of what the user wants.

**Comment by nemethviktor** [comment]
Ok try the usual dev place. Here's the thing though: if you're triggering the error because you have too many images, that should now be sorted. If you're on the other hand triggering because you have too many gpx/track files, then it's not likely to be sorted as I don't have a way around that particular issue for the time being. (reason is that image files can be consdered incoming data and i can filter that whereas gpx files are outgoing data, from the code's perspective, and i can't crop them.)

**Comment by lintujuh** [comment]
Seems to work.
