### ISSUE TITLE
Sorting by Taken Date sort alphabetically, not chronologically

### ISSUE THREAD

**Issue by lintujuh** [nemethviktor/GeoTagNinja#79]
**Describe the bug**
Sorting the file list by Taken Date column sorts the files incorrectly. The sort order is alphabetical, not chronological. I have the hours without leading zeros and images taken between 03 and 10 are sorted last.

**Expected behavior**
Sorting time columns sort according the time, not according the text strings.

**Screenshots**
![image](https://user-images.githubusercontent.com/5797282/226116495-cb35e1ab-fb0d-4a46-bcf0-d06d89467917.png)

**Desktop (please complete the following information):**
 - OS: Win11 Enterprise 22H2
 - Language/Culture: en-FI

**Additional context**
This is a not a major issue.

**Comment by nemethviktor** [comment]
Can you have a look pls on the usual dev-link.

A bit of a tl;dr but this is a complex change. 
Although the codebase has been moved a while ago to partially account for some of the various data types in certain contexts that change hasn't affected Sorting - a bit more fun is that the datatype of `DateTime` hasn't existed in the code so far so that had to be added in, which of course in turn threw off a few things.
This then coincided with me realising the whole of the Edit Form was still using `string` regardless of anything else _and_ while at it was not rebased to the updated code from a while ago properly so that has now been done as well. I think it should work okay but as always that's famous last words....
