### ISSUE TITLE
Hangs on startup

### ISSUE THREAD

**Issue by PeterBDa** [nemethviktor/GeoTagNinja#86]
When starting  (Windows 11 Home, Dutch language) "Please wait while the folder loads" popup plus error popup:  "De tekenreeks is niet als geldige DateTime herkend" (The string is not recognised as a valid Date Time) and then hangs. Only option is Ctrl-Alt-Delete.

Looks like issue #51

************** Tekst van uitzondering **************
System.FormatException: De tekenreeks is niet als geldige DateTime herkend.
   bij System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   bij GeoTagNinja.Model.DirectoryElement.ParseAttribute(ElementAttribute attribute, IDictionary`2 parsed_Values, List`1 parsed_Fails, IDictionary`2 tags, Int32 call_depth)
   bij GeoTagNinja.Model.DirectoryElement.ParseAttributesFromExifToolOutput(IDictionary`2 tags_in)
   bij GeoTagNinja.Model.DirectoryElementCollection.ParseFolderToDEs(String folder, Action`1 statusMethod)
   bij GeoTagNinja.FrmMainApp.lvwFileList_LoadOrUpdate()
   bij GeoTagNinja.FrmMainApp.<FrmMainApp_Load>d__64.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Geladen assembly's **************
mscorlib
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.9167.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
GeoTagNinja
    Assembly-versie: 0.8.8469.16211
    Win32-versie: 0.8.8469.16211
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/GeoTagNinja.exe
---------------------------------------- etc etc

**Comment by nemethviktor** [comment]
Hey, thanks for that, I'll have a look - not tested w Dutch so I'd need to
check.
Does it happen with any (all) picture or a specific one? If the latter, any
chance you could share that image? You can email me privately if preferred.

This message has been brought to you by my Huawei P30 Pro and myself. Any
typos blame the phone.

**Comment by PeterBDa** [comment]
It happens as soon as I try and open the application; before I get a chance to select pictures

**Comment by nemethviktor** [comment]
Ok I've had a look but admittedly I can't reproduce this as it works for me on Dutch W11 but I noticed that you're using a version that's pretty old (8469), there has been one release since plus there is a "dev" version at https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=drive_link -- can you try that please. Also to confirm that your datetime format setting (in Windows) is default, rather than custom?
The loading-folder thing actually involves reading data from the files, so if the version linked above is still failing then check the log file in c:\Users\Viktor\AppData\Roaming\GeoTagNinja\logfile.txt  (replace Viktor w your username ofc.) and see where it fails. You'll be looking for an ERROR or FATAL (prob the latter) around the part where it says something like `2023-07-28 18:47:05.7508|INFO|DirectoryElementCollection.ParseFolderOrFileListToDEs|Files: Extracting File Data` - there should be a list of files processed.

**Comment by PeterBDa** [comment]
The log shows a number (but not all) of the images in the root of my Pictures folder; no ERROR or FATAL message. If I remove the last image shown from the folder (one from the year 2008) the problem disappears. If I return it, the problem reappears. It is not impossible that this photo was taken with the camera of an American visitor. Anyway, this is obviously an incident and not a structural problem. Sorry for the false alarm.

**Comment by nemethviktor** [comment]
If you don't mind sharing that photo I'd still like to debug please. If you wish, you can email me at nemethv on Gmail.

**Comment by nemethviktor** [comment]
Received, thanks -- fwiw it's not Dutch that's an issue, does the same on EN-GB Windows as well. I'll have a look, possibly today, worst case tomorrow/monday.

**Comment by nemethviktor** [comment]
Right, try it now, same link as above but it's a patched version.

**Comment by PeterBDa** [comment]
Yes, my 'problematic' photo is no longer problematic. Thank you!
