### ISSUE TITLE
GeoTag write issue

### ISSUE THREAD

**Issue by lintujuh** [nemethviktor/GeoTagNinja#87]
**Describe the bug**
GeoTags written in the RAW file are not properly recognized by other software.

**To Reproduce**
I have updated the coordinates from a GPX file, and saved the edited files.

**Expected behavior**
All coordinates are properly interpreted by other programs.

**Screenshots**
See the attached example in my [Google drive](https://drive.google.com/drive/folders/1kFlKoXKcqFzRC-YLCbe2IcyD-sF7mOli?usp=sharing)
Geo information in my DAM (Daminion)
![image](https://github.com/nemethviktor/GeoTagNinja/assets/5797282/1ab41b1d-ef96-40ec-b776-5b692b60af62)
Geo information in my RAW processor (darktable).
![image](https://github.com/nemethviktor/GeoTagNinja/assets/5797282/9a6c9c02-92cf-4c30-920f-4fc0c38ba2dc)
And output from exiftool (EXIF section and Composite section)
![image](https://github.com/nemethviktor/GeoTagNinja/assets/5797282/d6efebea-3ec2-487b-aebe-a61d67545820)
![image](https://github.com/nemethviktor/GeoTagNinja/assets/5797282/71686a2e-7da7-4be6-a47c-036a49f17e94)

And how it looks in GeoTagNinja
![image](https://github.com/nemethviktor/GeoTagNinja/assets/5797282/7217760b-b26c-4cf3-acf5-ccad4bb53fd7)

All 

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise 22H2
 - Language/Culture: en-FI

**Additional context**

**Comment by nemethviktor** [comment]
Fascinating. So darktable only reads Composite, hence one is showing but the other isn't.

![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/7639d4a7-82a9-46bf-b7f0-e04369cbe493)

I'll have a look at forcing both to save.

**Comment by nemethviktor** [comment]
Any chance you could also post the GPX file to the same place pls?
If I just add a random coordinate (not via gpx) the values show okay. So I think the GPX import is not behaving properly.

**Comment by lintujuh** [comment]
Here is the GPX file.
[2023-03-02.zip](https://github.com/nemethviktor/GeoTagNinja/files/12318875/2023-03-02.zip)
Timezone is Lisbon.

**Comment by nemethviktor** [comment]
I'll fetch a Finnish/English copy of Windows, but in the meanwhile can you please ascertain you're running the latest release? (the one from about 2 weeks ago) -- basically I went through the process on an en-GB machine and it works as expected...

**Comment by nemethviktor** [comment]
Okay, I've tried on a Finnish/English version and while I can't reproduce that particular bug, I've found a different one - can you try  https://drive.google.com/open?id=18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0&usp=drive_fs and see if it's any better? Admittedly unsure I'd do much though.

**Comment by lintujuh** [comment]
It's now partially fixed. Darktable (dt) shows both the lat and long, but my DAM still doesn't recognize the coordinates. Also dt doesn't show the elevation. The differences I see are:
- for dt the GPS elevation, it is missing from composite (I had another image that had it, and there it is visible in dt)
- Daminion reads only the "raw" EXIF tags, and these are empty, only the elevation is there, and lat and long references
![image](https://github.com/nemethviktor/GeoTagNinja/assets/5797282/ae78f159-fabb-44fa-936c-6a4f14106d1a)

**Comment by nemethviktor** [comment]
Not sure what to do about Daminion I'm afraid - one is that i don't have a copy but also neither do the torrent sites. 

In the current GTN version that you have the exif-category data is there.

After about an hour of random trial-and-error I've found that the composite GPSAltitude is actually GPS:GPSAltitude (so we had some of the tags wrong) but on top of that would be ignored if we don't also explicitly specify that `GPS:GPSAltitudeRef=1` (which is, "above sea level") 

So currently I have this
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/20dd9dd1-544e-428b-a050-f8c88fe8dba2)

for DT then I think it's ok
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/13674582-262b-43d8-a8f9-3eafaf7fdae6)


for Daminion .... As I don't have a copy of it it's very difficult for me to debug, espc because the exif tags _are_ in the file as per above. So that one you'd need to debug on your own, to some extent anyway. 
Basically the args file (called `exifArgsToWrite.args`) as of now is

```
C:\temp\_3020304.ORF
-ignoreMinorErrors
-progress
-gps*=
-xmp:gps*=
-GPS:GPSAltitude=74.62
-GPS:GPSAltitudeRef=1
-exif:GPSAltitude=74.62
-exif:GPSAltitudeRef=1
-GPS:GPSLatitude=38.712259
-GPS:GPSLatitudeRef=North
-exif:GPSLatitude=38.712259
-exif:GPSLatitudeRef=North
-GPS:GPSLongitude=-9.131713
-GPS:GPSLongitudeRef=West
-exif:GPSLongitude=-9.131713
-exif:GPSLongitudeRef=West
-overwrite_original_in_place
-filemodifydate<datetimeoriginal
-filecreatedate<datetimeoriginal
-IPTCDigest=
-execute
```

there's some more stuff in it but things like city etc aren't relevant for our purposes
the command to execute is `exiftool -@ exifArgsToWrite.args`
you'd need to figure out a combination of tags from a combination of https://exiftool.org/TagNames/EXIF.html and https://exiftool.org/TagNames/GPS.html (pls don't tell me to f. off, I'd love to help but I don't have the program and I don't know what tags it's failing to read) that will work in Daminion.
Alternatively, if Daminion can _write_ files, tag your file with the right coordinates in Daminion, save it and put it to g-drive so I can try to have a look.

I've copied an updated setup file to the earlier location. The composite tags should save okay now I think.

**Comment by nemethviktor** [comment]
I've been thinking about this a little. If you have any (preferably ORF file) that was saved by just about any software, or you found it online, not important, that Daminion can read and has the right sort of information and it shows as you'd like, send it on. I think it's probably trying to read a particular exif tag ID that we're either unaware of or it just needs to be explicitly saved somehow.

**Comment by lintujuh** [comment]
Thank you Viktor!

I have forwarded your findings to the vendor of Daminion. They have been
very supportive to me as I'm running a beta version of their software. It
looks now that the issue is at their end. I have asked them to give
feedback, if there is something still wrong with the tags.

darktable reads and exports now the latitude, longitude and altitude
correctly to the jpg from the raw.

-.Juha

**Comment by nemethviktor** [comment]
Glad to hear :) -- ok keep me posted, if it turns out to be ok on this end close the ticket pls ;)

**Comment by lintujuh** [comment]
I will.

-Juha

**Comment by lintujuh** [comment]
Hi Viktor,

There was a bug in reading the geotags in Daminion. I got a test version
where it is now fixed.

-Juha

**Comment by nemethviktor** [comment]
Yayy, glad to hear :)
