### ISSUE TITLE
1 files weren't updated due to errors

### ISSUE THREAD

**Issue by NO-MAN-CAT** [nemethviktor/GeoTagNinja#98]
**Describe the bug**
The problem occurs when adding and **saving** GPS **data to photos**.
If I add GPS data for two or more photos (probably an issue with the loop), the program throws a critical error and does not work.
However, if I add GPS data only for the one photo and save, everything works fine - the program adds and saves GPS data to the photo.
The specific moment when the error occurs is during saving.

**To Reproduce**
I can consistently reproduce the error https://youtu.be/2dFKn5e1cDo?si=rslixTw-w7Cdeori 
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/2808f5ef-ec3c-40fb-9c8d-65d9f8d46060)
I noticed that if I remove the long path containing Cyrillic characters and spaces to something simpler - E:\desktop\geo, the error does not occur.

**Expected behavior**
Error shouldn't pop. 

**Desktop (please complete the following information):**
Microsoft Windows Version [10.0.19044.2130] LTSC.
Language/Culture [e.g. en-US]
Failing path where I placed the photos - E:\desktop\вакарбуля\jpgs to watermark\desktop\вакарбуля\jpgs to watermark\.
Also,

**Comment by nemethviktor** [comment]
Hi, 

I this is mentioned in the readme/known issues - exiftool has an issue with special-character paths, which is why the process works when you move the files into a path the doesn't have UTF characters in it. 
Have you enabled this -> https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do function? [ignore the c# part in the stackoverflow post, just try turning on the unicode support and restart, it might help]

**Comment by nemethviktor** [comment]
Hmm, ok, I'll have a look, will report back soonish.

**Comment by nemethviktor** [comment]
Ok to be honest I've done a bit of digging and I'm not any smarter. The problem is that the error message you get is basically an output of exifTool and the GTN app just relays that to the user, so I can't even set a breakpoint or catch it properly (I can, but I wouldn't get any exception details is the point). I don't understand why it works once but not afterwards, not the least because I can't repro it _in command-line_ (in the app I can but that isn't ultimately relevant because it boils down to the cmd version - see below) :
The way GTN works is that when the user presses 'save', a so-called arguments file is created in c:\Users\user\AppData\Roaming\GeoTagNinja\  folder - that file gets deleted when the folder refreshes so if you are curious about its contents then given that you get an error message try to view it while the app is showing the error message.
If you want to execute the contents of the file you need to do `exiftool.exe -@ c:\Users\user\AppData\Roaming\GeoTagNinja\exifArgsToWrite.args`
I've installed a version of Win10 LTSC and run the above command on a random set of untagged photos. 
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/cfa66696-1557-4975-a77a-16720a1ba4f4)

You'll notice that Win10 is having issues deciphering the Cyrillic characters, which is why it fails. It even fails for the first one. **However:** if you enable the setting I mentioned above and restart, the cmd works okay

![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/7c062ee0-2e4f-4c8f-80be-2d6494d1040a)

I've also tried in GTN after enabling the setting and that works too.

**Comment by NO-MAN-CAT** [comment]
I decided to narrow down the root cause, whether it is due to Cyrillic characters or whitespace. It seems that Cyrillic characters in the path are causing this
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/e021b732-c6cb-4532-92df-345e0d7d5a36)


I applied the suggested
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/cc526d6f-bdc3-492e-8d44-c4f359a88f7f)

Retested and it doesn't fail anymore with Cyrillic path.
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/8289d59a-5b99-4923-9961-a9a1bc9a4450)
